package com.meteor.extrabotany.client.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.inventory.EntityEquipmentSlot;
import vazkii.botania.client.model.armor.ModelArmor;

import javax.annotation.Nonnull;

public class ModelArmorGoblinSlayer extends ModelArmor{
	
	private final ModelRenderer helmAnchor;  
	private final ModelRenderer bodyAnchor;
	private final ModelRenderer body;	
	private final ModelRenderer armLAnchor;
    private final ModelRenderer armRAnchor;
	private final ModelRenderer pantsAnchor;
    private final ModelRenderer legL;
    private final ModelRenderer legR; 
    
    ModelRenderer head;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer FTop;
    ModelRenderer FFace7;
    ModelRenderer FFace8;
    ModelRenderer FFace2;
    ModelRenderer FtopF;
    ModelRenderer FFace6;
    ModelRenderer FFace5;
    ModelRenderer FFace4;
    ModelRenderer FFace3;
    ModelRenderer FFace1;
    ModelRenderer FLeftT;
    ModelRenderer FRightT;
    ModelRenderer FTop7;
    ModelRenderer FBack;
    ModelRenderer FTop5;
    ModelRenderer FTop6;
    ModelRenderer FLeft;
    ModelRenderer FTop4;
    ModelRenderer Ftop2;
    ModelRenderer FRight;
    ModelRenderer FTop3;
    ModelRenderer BBack;
    ModelRenderer BFront1;
    ModelRenderer BT4;
    ModelRenderer BodySMallBag;
    ModelRenderer BodyBigPack;
    ModelRenderer BBB;
    ModelRenderer BDT;
    ModelRenderer BT3;
    ModelRenderer BT2;
    ModelRenderer BT1;
    ModelRenderer BFront4;
    ModelRenderer BFront3;
    ModelRenderer BFront2;
    ModelRenderer ALUp1;
    ModelRenderer ALUp2;
    ModelRenderer ALA;
    ModelRenderer ALeftT2;
    ModelRenderer ALeftT1;
    ModelRenderer ARUp1;
    ModelRenderer ARUp2;
    ModelRenderer ARA;
    ModelRenderer ARightT1;
    ModelRenderer ARightT2;
    ModelRenderer LL1;
    ModelRenderer LLT;
    ModelRenderer LL2;
    ModelRenderer LL3;
    ModelRenderer LR1;
    ModelRenderer LRT;
    ModelRenderer LR2;
    ModelRenderer LR3;

	public ModelArmorGoblinSlayer(EntityEquipmentSlot slot) {
		super(slot);
		
		this.textureWidth = 128;
        this.textureHeight = 128;
		float s = 0.01F;
		
		//helm
        this.helmAnchor = new ModelRenderer(this, 0, 0);
        this.helmAnchor.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.helmAnchor.addBox(-1.0F, -2.0F, 0.0F, 2, 2, 2, s);
        
        //body
        this.bodyAnchor = new ModelRenderer(this, 0, 0);
        this.bodyAnchor.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.bodyAnchor.addBox(-1.0F, 0.0F, -1.0F, 2, 2, 2, s);
                
     	//armL
        this.armLAnchor = new ModelRenderer(this, 0, 0);
        this.armLAnchor.mirror = true;
        this.armLAnchor.setRotationPoint(4.0F, 2.0F, 0.0F);
        this.armLAnchor.addBox(0.0F, -1.0F, -1.0F, 2, 2, 2, s);
        
        //armR
        this.armRAnchor = new ModelRenderer(this, 0, 0);
        this.armRAnchor.mirror = true;
        this.armRAnchor.setRotationPoint(-4.0F, 2.0F, 0.0F);
        this.armRAnchor.addBox(-2.0F, -1.0F, -1.0F, 2, 2, 2, s);
        
        //pants
        this.pantsAnchor = new ModelRenderer(this, 0, 0);
        this.pantsAnchor.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pantsAnchor.addBox(-1.0F, 0.0F, -1.0F, 2, 2, 2, s);           
        this.legR = new ModelRenderer(this, 0, 16);
        this.legR.addBox(-2F, 0F, -2F, 4, 12, 4, s);
        this.legR.setRotationPoint(-2F, 12F, 0F);
        this.legR.setTextureSize(64, 32);
        this.legR.mirror = true;
        this.setRotateAngle(legR, 0F, 0F, 0F);
        this.legL = new ModelRenderer(this, 0, 16);
        this.legL.addBox(-2F, 0F, -2F, 4, 12, 4, s);
        this.legL.setRotationPoint(2F, 12F, 0F);
        this.legL.setTextureSize(64, 32);
        this.legL.mirror = true;
        this.setRotateAngle(legL, 0F, 0F, 0F);
        
        head = new ModelRenderer(this, 0, 50);
        head.addBox(-4F, -8F, -4F, 8, 8, 8,s);
        head.setRotationPoint(0F, 0F, 0F);
        head.setTextureSize(64, 32);
        head.mirror = true;
        setRotateAngle(head, 0F, 0F, 0F);     
        body = new ModelRenderer(this, 16, 66);
        body.addBox(-4F, 0F, -2F, 8, 12, 4,s);
        body.setRotationPoint(0F, 0F, 0F);
        body.setTextureSize(64, 32);
        body.mirror = true;
        setRotateAngle(body, 0F, 0F, 0F);
        rightarm = new ModelRenderer(this, 40, 66);
        rightarm.addBox(-3F, -2F, -2F, 4, 12, 4,s);
        rightarm.setRotationPoint(0F, 0F, 0F);
        rightarm.setTextureSize(64, 32);
        rightarm.mirror = true;
        setRotateAngle(rightarm, 0F, 0F, 0F);
        leftarm = new ModelRenderer(this, 40, 66);
        leftarm.addBox(-1F, -2F, -2F, 4, 12, 4,s);
        leftarm.setRotationPoint(0F, 0F, 0F);
        leftarm.setTextureSize(64, 32);
        leftarm.mirror = true;
        setRotateAngle(leftarm, 0F, 0F, 0F);
        rightleg = new ModelRenderer(this, 0, 66);
        rightleg.addBox(-2F, 0F, -2F, 4, 12, 4,s);
        rightleg.setRotationPoint(0F, 0F, 0F);
        rightleg.setTextureSize(64, 32);
        rightleg.mirror = true;
        setRotateAngle(rightleg, 0F, 0F, 0F);
        leftleg = new ModelRenderer(this, 0, 66);
        leftleg.addBox(-2F, 0F, -2F, 4, 12, 4,s);
        leftleg.setRotationPoint(0F, 0F, 0F);
        leftleg.setTextureSize(64, 32);
        leftleg.mirror = true;
        setRotateAngle(leftleg, 0F, 0F, 0F);
        FTop = new ModelRenderer(this, 0, 0);
        FTop.addBox(0F, 0F, 0F, 8, 1, 8);
        FTop.setRotationPoint(0.2F, -7.3F, -8F);
        FTop.setTextureSize(64, 32);
        FTop.mirror = true;
        setRotateAngle(FTop, 0.3141593F, -0.7679449F, -0.246706F);
        FFace7 = new ModelRenderer(this, 0, 0);
        FFace7.addBox(-4F, 0F, 0F, 8, 2, 1);
        FFace7.setRotationPoint(0F, -2F, -5F);
        FFace7.setTextureSize(64, 32);
        FFace7.mirror = true;
        setRotateAngle(FFace7, 0.2617994F, 0F, 0F);
        FFace8 = new ModelRenderer(this, 0, 0);
        FFace8.addBox(-2F, 0F, 0F, 3, 2, 1);
        FFace8.setRotationPoint(0.5F, -1F, -5F);
        FFace8.setTextureSize(64, 32);
        FFace8.mirror = true;
        setRotateAngle(FFace8, 0.2617994F, 0F, 0F);
        FFace2 = new ModelRenderer(this, 0, 0);
        FFace2.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace2.setRotationPoint(4.4F, -7F, -5F);
        FFace2.setTextureSize(64, 32);
        FFace2.mirror = true;
        setRotateAngle(FFace2, 0.1047198F, 0F, 0.0872665F);
        FtopF = new ModelRenderer(this, 0, 35);
        FtopF.addBox(0F, 0F, 0F, 4, 1, 4);
        FtopF.setRotationPoint(-2F, -11F, 2F);
        FtopF.setTextureSize(64, 32);
        FtopF.mirror = true;
        setRotateAngle(FtopF, 0.2617994F, 0F, 0F);
        FFace6 = new ModelRenderer(this, 0, 0);
        FFace6.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace6.setRotationPoint(3.4F, -7F, -5F);
        FFace6.setTextureSize(64, 32);
        FFace6.mirror = true;
        setRotateAngle(FFace6, 0.122173F, 0F, 0.0872665F);
        FFace5 = new ModelRenderer(this, 0, 0);
        FFace5.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace5.setRotationPoint(-3.5F, -7F, -5.2F);
        FFace5.setTextureSize(64, 32);
        FFace5.mirror = true;
        setRotateAngle(FFace5, 0.1396263F, 0F, -0.122173F);
        FFace4 = new ModelRenderer(this, 0, 0);
        FFace4.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace4.setRotationPoint(-0.5F, -7F, -5.2F);
        FFace4.setTextureSize(64, 32);
        FFace4.mirror = true;
        setRotateAngle(FFace4, 0.122173F, 0F, -0.0349066F);
        FFace3 = new ModelRenderer(this, 0, 0);
        FFace3.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace3.setRotationPoint(1.5F, -7F, -5.2F);
        FFace3.setTextureSize(64, 32);
        FFace3.mirror = true;
        setRotateAngle(FFace3, 0.122173F, 0F, 0.0349066F);
        FFace1 = new ModelRenderer(this, 0, 0);
        FFace1.addBox(-1F, 0F, 0F, 1, 7, 1);
        FFace1.setRotationPoint(-2.5F, -7F, -5.2F);
        FFace1.setTextureSize(64, 32);
        FFace1.mirror = true;
        setRotateAngle(FFace1, 0.122173F, 0F, -0.0872665F);
        FLeftT = new ModelRenderer(this, 0, 0);
        FLeftT.addBox(0F, 0F, 0F, 2, 2, 2);
        FLeftT.setRotationPoint(4F, -5F, -1F);
        FLeftT.setTextureSize(64, 32);
        FLeftT.mirror = true;
        setRotateAngle(FLeftT, 0F, 0F, 0F);
        FRightT = new ModelRenderer(this, 0, 0);
        FRightT.addBox(0F, 0F, 0F, 2, 2, 2);
        FRightT.setRotationPoint(-6F, -5F, -1F);
        FRightT.setTextureSize(64, 32);
        FRightT.mirror = true;
        setRotateAngle(FRightT, 0F, 0F, 0F);
        FTop7 = new ModelRenderer(this, 0, 0);
        FTop7.addBox(-4.5F, 0F, 0F, 9, 1, 4);
        FTop7.setRotationPoint(0F, -8F, 1F);
        FTop7.setTextureSize(64, 32);
        FTop7.mirror = true;
        setRotateAngle(FTop7, 0.1745329F, 0F, 0F);
        FBack = new ModelRenderer(this, 0, 0);
        FBack.addBox(0F, -7F, 0F, 8, 8, 1);
        FBack.setRotationPoint(-4F, -1F, 3.4F);
        FBack.setTextureSize(64, 32);
        FBack.mirror = true;
        setRotateAngle(FBack, -0.0872665F, 0F, 0F);
        FTop5 = new ModelRenderer(this, 0, 0);
        FTop5.addBox(0F, 0F, -2F, 3, 1, 5);
        FTop5.setRotationPoint(3F, -9.6F, -1F);
        FTop5.setTextureSize(64, 32);
        FTop5.mirror = true;
        setRotateAngle(FTop5, 0F, 0F, 0.3839724F);
        FTop6 = new ModelRenderer(this, 0, 0);
        FTop6.addBox(-3.5F, 0F, 0F, 7, 1, 4);
        FTop6.setRotationPoint(0F, -10F, 0F);
        FTop6.setTextureSize(64, 32);
        FTop6.mirror = true;
        setRotateAngle(FTop6, -0.3316126F, 0F, 0F);
        FLeft = new ModelRenderer(this, 0, 0);
        FLeft.addBox(0F, 0F, 0F, 1, 8, 9);
        FLeft.setRotationPoint(3.4F, -8F, -4.5F);
        FLeft.setTextureSize(64, 32);
        FLeft.mirror = true;
        setRotateAngle(FLeft, 0F, 0F, 0.0523599F);
        FTop4 = new ModelRenderer(this, 0, 0);
        FTop4.addBox(0F, 0F, -2F, 3, 1, 5);
        FTop4.setRotationPoint(-5.8F, -8.6F, -1F);
        FTop4.setTextureSize(64, 32);
        FTop4.mirror = true;
        setRotateAngle(FTop4, 0F, 0F, -0.3839724F);
        Ftop2 = new ModelRenderer(this, 0, 0);
        Ftop2.addBox(0F, 0F, 0F, 6, 1, 6);
        Ftop2.setRotationPoint(0F, -8.5F, -6F);
        Ftop2.setTextureSize(64, 32);
        Ftop2.mirror = true;
        setRotateAngle(Ftop2, 0.2268928F, -0.7679449F, -0.2268928F);
        FRight = new ModelRenderer(this, 0, 0);
        FRight.addBox(0F, 0F, 0F, 1, 8, 9);
        FRight.setRotationPoint(-4.6F, -8F, -4.5F);
        FRight.setTextureSize(64, 32);
        FRight.mirror = true;
        setRotateAngle(FRight, 0F, 0F, -0.0523599F);
        FTop3 = new ModelRenderer(this, 0, 0);
        FTop3.addBox(0F, 0F, 0F, 5, 1, 5);
        FTop3.setRotationPoint(0F, -9.6F, -5F);
        FTop3.setTextureSize(64, 32);
        FTop3.mirror = true;
        setRotateAngle(FTop3, 0.1396263F, -0.7679449F, -0.1396263F);
        BBack = new ModelRenderer(this, 0, 0);
        BBack.addBox(-4F, 0F, 0F, 8, 7, 1);
        BBack.setRotationPoint(0F, 1F, 1.6F);
        BBack.setTextureSize(64, 32);
        BBack.mirror = true;
        setRotateAngle(BBack, 0F, 0F, 0F);
        BFront1 = new ModelRenderer(this, 0, 0);
        BFront1.addBox(0F, 0F, 0F, 4, 3, 1);
        BFront1.setRotationPoint(1F, 1F, -2.5F);
        BFront1.setTextureSize(64, 32);
        BFront1.mirror = true;
        setRotateAngle(BFront1, -0.0872665F, 0.0872665F, 0.6108652F);
        BT4 = new ModelRenderer(this, 0, 0);
        BT4.addBox(0F, 0F, 0F, 1, 1, 5);
        BT4.setRotationPoint(-4.1F, 2F, -2.5F);
        BT4.setTextureSize(64, 32);
        BT4.mirror = true;
        setRotateAngle(BT4, 0F, 0F, 0.3490659F);
        BodySMallBag = new ModelRenderer(this, 0, 0);
        BodySMallBag.addBox(0F, 0F, 0F, 1, 1, 1);
        BodySMallBag.setRotationPoint(-4F, 11F, -2.4F);
        BodySMallBag.setTextureSize(64, 32);
        BodySMallBag.mirror = true;
        setRotateAngle(BodySMallBag, 0F, 0F, 0F);
        BodyBigPack = new ModelRenderer(this, 0, 22);
        BodyBigPack.addBox(0F, 0F, 0F, 2, 2, 6);
        BodyBigPack.setRotationPoint(3.5F, 10F, -3F);
        BodyBigPack.setTextureSize(64, 32);
        BodyBigPack.mirror = true;
        setRotateAngle(BodyBigPack, -0.1745329F, -0.0174533F, 0F);
        BBB = new ModelRenderer(this, 0, 0);
        BBB.addBox(0F, 0F, 0F, 6, 3, 1,s);
        BBB.setRotationPoint(-3F, 10.5F, 1.6F);
        BBB.setTextureSize(64, 32);
        BBB.mirror = true;
        setRotateAngle(BBB, 0.122173F, 0F, 0F);
        BDT = new ModelRenderer(this, 0, 0);
        BDT.addBox(0F, 0F, 0F, 9, 1, 5,s);
        BDT.setRotationPoint(-4.5F, 10.6F, -2.4F);
        BDT.setTextureSize(64, 32);
        BDT.mirror = true;
        setRotateAngle(BDT, 0F, 0F, 0F);
        BT3 = new ModelRenderer(this, 0, 0);
        BT3.addBox(-1F, 0F, 0F, 1, 1, 5,s);
        BT3.setRotationPoint(4.1F, 2F, -2.5F);
        BT3.setTextureSize(64, 32);
        BT3.mirror = true;
        setRotateAngle(BT3, 0F, 0F, -0.3490659F);
        BT2 = new ModelRenderer(this, 0, 0);
        BT2.addBox(0F, 0F, 0F, 1, 1, 5,s);
        BT2.setRotationPoint(-4.1F, 7F, -2.5F);
        BT2.setTextureSize(64, 32);
        BT2.mirror = true;
        setRotateAngle(BT2, 0F, -0.0174533F, 0F);
        BT1 = new ModelRenderer(this, 0, 0);
        BT1.addBox(0F, 0F, 0F, 1, 1, 5);
        BT1.setRotationPoint(3.1F, 7F, -2.5F);
        BT1.setTextureSize(64, 32);
        BT1.mirror = true;
        setRotateAngle(BT1, 0F, 0.0174533F, 0F);
        BFront4 = new ModelRenderer(this, 0, 0);
        BFront4.addBox(0F, 0F, 0F, 5, 5, 1);
        BFront4.setRotationPoint(0F, 3.8F, -2.5F);
        BFront4.setTextureSize(64, 32);
        BFront4.mirror = true;
        setRotateAngle(BFront4, 0.0174533F, 0F, 0.7853982F);
        BFront3 = new ModelRenderer(this, 0, 0);
        BFront3.addBox(0F, 0F, 0F, 5, 5, 1,s);
        BFront3.setRotationPoint(0F, 1.7F, -2.5F);
        BFront3.setTextureSize(64, 32);
        BFront3.mirror = true;
        setRotateAngle(BFront3, -0.0872665F, 0.0872665F, 0.7853982F);
        BFront2 = new ModelRenderer(this, 0, 0);
        BFront2.addBox(-4F, 0F, 0F, 4, 3, 1,s);
        BFront2.setRotationPoint(-1F, 1F, -2.5F);
        BFront2.setTextureSize(64, 32);
        BFront2.mirror = true;
        setRotateAngle(BFront2, -0.0872665F, -0.0872665F, -0.6632251F);
        ALUp1 = new ModelRenderer(this, 0, 0);
        ALUp1.addBox(0F, 0F, 0F, 5, 3, 6);
        ALUp1.setRotationPoint(0F, -3F, -3F);
        ALUp1.setTextureSize(64, 32);
        ALUp1.mirror = true;
        setRotateAngle(ALUp1, 0F, 0F, 0.2617994F);
        ALUp2 = new ModelRenderer(this, 0, 0);
        ALUp2.addBox(0F, 0F, 0F, 4, 3, 5);
        ALUp2.setRotationPoint(0.5F, -1.5F, -2.5F);
        ALUp2.setTextureSize(64, 32);
        ALUp2.mirror = true;
        setRotateAngle(ALUp2, 0F, 0F, 0.2617994F);
        ALA = new ModelRenderer(this, 0, 0);
        ALA.addBox(0F, 0F, 0F, 2, 5, 5);
        ALA.setRotationPoint(1.5F, 4F, -2.5F);
        ALA.setTextureSize(64, 32);
        ALA.mirror = true;
        setRotateAngle(ALA, 0F, 0F, 0F);
        ALeftT2 = new ModelRenderer(this, 0, 0);
        ALeftT2.addBox(0F, 0F, 0F, 3, 1, 5);
        ALeftT2.setRotationPoint(-1.5F, 7.5F, -2.5F);
        ALeftT2.setTextureSize(64, 32);
        ALeftT2.mirror = true;
        setRotateAngle(ALeftT2, 0F, 0F, 0F);
        ALeftT1 = new ModelRenderer(this, 0, 0);
        ALeftT1.addBox(0F, 0F, 0F, 3, 1, 5);
        ALeftT1.setRotationPoint(-1.5F, 4.5F, -2.5F);
        ALeftT1.setTextureSize(64, 32);
        ALeftT1.mirror = true;
        setRotateAngle(ALeftT1, 0F, 0F, 0F);
        ARUp1 = new ModelRenderer(this, 0, 0);
        ARUp1.addBox(-5F, 0F, 0F, 5, 3, 6);
        ARUp1.setRotationPoint(0F, -3F, -3F);
        ARUp1.setTextureSize(64, 32);
        ARUp1.mirror = true;
        setRotateAngle(ARUp1, 0F, 0F, -0.2617994F);
        ARUp2 = new ModelRenderer(this, 0, 0);
        ARUp2.addBox(-4F, 0F, 0F, 4, 3, 5);
        ARUp2.setRotationPoint(-0.5F, -1.5F, -2.5F);
        ARUp2.setTextureSize(64, 32);
        ARUp2.mirror = true;
        setRotateAngle(ARUp2, 0F, 0F, -0.2617994F);
        ARA = new ModelRenderer(this, 0, 0);
        ARA.addBox(0F, 0F, 0F, 2, 5, 5);
        ARA.setRotationPoint(-3.5F, 4F, -2.5F);
        ARA.setTextureSize(64, 32);
        ARA.mirror = true;
        setRotateAngle(ARA, 0F, 0F, 0F);
        ARightT1 = new ModelRenderer(this, 0, 0);
        ARightT1.addBox(0F, 0F, 0F, 3, 1, 5);
        ARightT1.setRotationPoint(-1.5F, 4.5F, -2.5F);
        ARightT1.setTextureSize(64, 32);
        ARightT1.mirror = true;
        setRotateAngle(ARightT1, 0F, 0F, 0F);
        ARightT2 = new ModelRenderer(this, 0, 0);
        ARightT2.addBox(0F, 0F, 0F, 3, 1, 5);
        ARightT2.setRotationPoint(-1.5F, 7.5F, -2.5F);
        ARightT2.setTextureSize(64, 32);
        ARightT2.mirror = true;
        setRotateAngle(ARightT2, 0F, 0F, 0F);
        LL1 = new ModelRenderer(this, 0, 0);
        LL1.addBox(0F, 0F, 0F, 4, 3, 2,s);
        LL1.setRotationPoint(-1.7F, 0.3F, -2.5F);
        LL1.setTextureSize(64, 32);
        LL1.mirror = true;
        setRotateAngle(LL1, 0F, 0.0174533F, 0F);
        LLT = new ModelRenderer(this, 0, 0);
        LLT.addBox(0F, 0F, 0F, 5, 1, 5,s);
        LLT.setRotationPoint(-2.5F, 4.5F, -2.4F);
        LLT.setTextureSize(64, 32);
        LLT.mirror = true;
        setRotateAngle(LLT, 0F, -0.0174533F, 0F);
        LL2 = new ModelRenderer(this, 0, 0);
        LL2.addBox(-4F, 0F, 0F, 3, 2, 1,s);
        LL2.setRotationPoint(2.5F, 4F, -2.5F);
        LL2.setTextureSize(64, 32);
        LL2.mirror = true;
        setRotateAngle(LL2, 0F, -0.0174533F, 0F);
        LL3 = new ModelRenderer(this, 0, 0);
        LL3.addBox(-4F, 0F, 0F, 4, 4, 5,s);
        LL3.setRotationPoint(2.3F, 6.5F, -2.5F);
        LL3.setTextureSize(64, 32);
        LL3.mirror = true;
        setRotateAngle(LL3, 0F, 0F, 0F);
        LR1 = new ModelRenderer(this, 0, 0);
        LR1.addBox(-4F, 0F, 0F, 4, 3, 2,s);
        LR1.setRotationPoint(1.7F, 0.3F, -2.5F);
        LR1.setTextureSize(64, 32);
        LR1.mirror = true;
        setRotateAngle(LR1, 0F, 0F, 0F);
        LRT = new ModelRenderer(this, 0, 0);
        LRT.addBox(0F, 0F, 0F, 5, 1, 5,s);
        LRT.setRotationPoint(-2.5F, 4.5F, -2.4F);
        LRT.setTextureSize(64, 32);
        LRT.mirror = true;
        setRotateAngle(LRT, 0F, 0F, 0F);
        LR2 = new ModelRenderer(this, 0, 0);
        LR2.addBox(-4F, 0F, 0F, 3, 2, 1,s);
        LR2.setRotationPoint(2.5F, 4F, -2.5F);
        LR2.setTextureSize(64, 32);
        LR2.mirror = true;
        setRotateAngle(LR2, 0F, 0.0174533F, 0F);
        LR3 = new ModelRenderer(this, 0, 0);
        LR3.addBox(-4F, 0F, 0F, 4, 4, 5,s);
        LR3.setRotationPoint(1.7F, 6.5F, -2.5F);
        LR3.setTextureSize(64, 32);
        LR3.mirror = true;
        setRotateAngle(LR3, 0F, 0F, 0F);
        
        this.helmAnchor.addChild(this.FBack);
        this.helmAnchor.addChild(this.FFace1);
        this.helmAnchor.addChild(this.FFace2);
        this.helmAnchor.addChild(this.FFace3);
        this.helmAnchor.addChild(this.FFace4);
        this.helmAnchor.addChild(this.FFace5);
        this.helmAnchor.addChild(this.FFace6);
        this.helmAnchor.addChild(this.FFace7);
        this.helmAnchor.addChild(this.FFace8);
        this.helmAnchor.addChild(this.FLeft);
        this.helmAnchor.addChild(this.FLeftT);
        this.helmAnchor.addChild(this.FRight);
        this.helmAnchor.addChild(this.FRightT);
        this.helmAnchor.addChild(this.Ftop2);
        this.helmAnchor.addChild(this.FTop3);
        this.helmAnchor.addChild(this.FTop4);
        this.helmAnchor.addChild(this.FTop5);
        this.helmAnchor.addChild(this.FTop6);
        this.helmAnchor.addChild(this.FTop7);
        this.helmAnchor.addChild(this.FtopF);
        this.helmAnchor.addChild(this.head);
        this.head.addChild(this.FTop);
        
        this.bodyAnchor.addChild(this.body);
        this.body.addChild(this.BBack);
        this.body.addChild(this.BBB);
        this.body.addChild(this.BDT);
        this.body.addChild(this.BFront1);
        this.body.addChild(this.BFront2);
        this.body.addChild(this.BFront3);
        this.body.addChild(this.BFront4);
        this.body.addChild(this.BodyBigPack);
        this.body.addChild(this.BodySMallBag);
        this.body.addChild(this.BT1);
        this.body.addChild(this.BT2);
        this.body.addChild(this.BT3);
        this.body.addChild(this.BT4);
        
        this.armLAnchor.addChild(this.ALA);
        this.armLAnchor.addChild(this.ALeftT1);
        this.armLAnchor.addChild(this.ALeftT2);
        this.armLAnchor.addChild(this.ALUp1);
        this.armLAnchor.addChild(this.ALUp2);
        
        this.armRAnchor.addChild(this.ARA);
        this.armRAnchor.addChild(this.ARightT1);
        this.armRAnchor.addChild(this.ARightT2);
        this.armRAnchor.addChild(this.ARUp1);
        this.armRAnchor.addChild(this.ARUp2);
        
        this.legR.addChild(this.LR1);
        this.legR.addChild(this.LR2);
        this.legR.addChild(this.LR3);
        this.legR.addChild(this.LRT);
        
        this.legL.addChild(this.LL1);
        this.legL.addChild(this.LL2);
        this.legL.addChild(this.LL3);
        this.legL.addChild(this.LLT);
	}
	
	@Override
	public void render(@Nonnull Entity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {

		helmAnchor.showModel = slot == EntityEquipmentSlot.HEAD;
		bodyAnchor.showModel = slot == EntityEquipmentSlot.CHEST;
		armRAnchor.showModel = slot == EntityEquipmentSlot.CHEST;
		armLAnchor.showModel = slot == EntityEquipmentSlot.CHEST;
		legR.showModel = slot == EntityEquipmentSlot.LEGS;
		legL.showModel = slot == EntityEquipmentSlot.LEGS;
		bipedHeadwear.showModel = false;

		bipedHead = helmAnchor;
		bipedBody = bodyAnchor;
		bipedRightArm = armRAnchor;
		bipedLeftArm = armLAnchor;
		if(slot == EntityEquipmentSlot.LEGS) {
			bipedBody = pantsAnchor;
			bipedRightLeg = legR;
			bipedLeftLeg = legL;
		} else {

		}
		
		super.render(entity, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
	}

}
