// Date: 2019/3/2 22:37:11
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package net.minecraft.src;

public class Modelvoid extends ModelBase {
    //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer rightarmlayer;
    ModelRenderer headlayer;
    ModelRenderer leftleglayer;
    ModelRenderer rightleglayer;
    ModelRenderer bodylayer;
    ModelRenderer leftarmlayer;
    ModelRenderer winga;
    ModelRenderer wingb;
    ModelRenderer Shape;
    ModelRenderer Piece1;

    public Modelvoid() {
        textureWidth = 128;
        textureHeight = 128;

        head = new ModelRenderer(this, 0, 0);
        head.addBox(-4F, -8F, -4F, 8, 8, 8);
        head.setRotationPoint(0F, 0F, 0F);
        head.setTextureSize(128, 128);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body = new ModelRenderer(this, 16, 16);
        body.addBox(-4F, 0F, -2F, 8, 12, 4);
        body.setRotationPoint(0F, 0F, 0F);
        body.setTextureSize(128, 128);
        body.mirror = true;
        setRotation(body, 0F, 0F, 0F);
        rightarm = new ModelRenderer(this, 40, 16);
        rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
        rightarm.setRotationPoint(-5F, 2F, 0F);
        rightarm.setTextureSize(128, 128);
        rightarm.mirror = true;
        setRotation(rightarm, 0F, 0F, 0F);
        leftarm = new ModelRenderer(this, 40, 16);
        leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
        leftarm.setRotationPoint(5F, 2F, 0F);
        leftarm.setTextureSize(128, 128);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, 0F);
        rightleg = new ModelRenderer(this, 0, 16);
        rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
        rightleg.setRotationPoint(-2F, 12F, 0F);
        rightleg.setTextureSize(128, 128);
        rightleg.mirror = true;
        setRotation(rightleg, 0F, 0F, 0F);
        leftleg = new ModelRenderer(this, 0, 16);
        leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
        leftleg.setRotationPoint(2F, 12F, 0F);
        leftleg.setTextureSize(128, 128);
        leftleg.mirror = true;
        setRotation(leftleg, 0F, 0F, 0F);
        rightarmlayer = new ModelRenderer(this, 16, 48);
        rightarmlayer.addBox(0F, 0F, 0F, 4, 12, 4);
        rightarmlayer.setRotationPoint(-8F, 0F, -2F);
        rightarmlayer.setTextureSize(128, 128);
        rightarmlayer.mirror = true;
        setRotation(rightarmlayer, 0F, 0F, 0F);
        headlayer = new ModelRenderer(this, 32, 0);
        headlayer.addBox(0F, 0F, 0F, 8, 8, 8);
        headlayer.setRotationPoint(-4F, -8F, -4F);
        headlayer.setTextureSize(128, 128);
        headlayer.mirror = true;
        setRotation(headlayer, 0F, 0F, 0F);
        leftleglayer = new ModelRenderer(this, 0, 48);
        leftleglayer.addBox(0F, 0F, 0F, 4, 12, 4);
        leftleglayer.setRotationPoint(0F, 12F, -2F);
        leftleglayer.setTextureSize(128, 128);
        leftleglayer.mirror = true;
        setRotation(leftleglayer, 0F, 0F, 0F);
        rightleglayer = new ModelRenderer(this, 0, 32);
        rightleglayer.addBox(0F, 0F, 0F, 4, 12, 4);
        rightleglayer.setRotationPoint(-4F, 12F, -2F);
        rightleglayer.setTextureSize(128, 128);
        rightleglayer.mirror = true;
        setRotation(rightleglayer, 0F, 0F, 0F);
        bodylayer = new ModelRenderer(this, 16, 32);
        bodylayer.addBox(0F, 0F, 0F, 8, 12, 4);
        bodylayer.setRotationPoint(-4F, 0F, -2F);
        bodylayer.setTextureSize(128, 128);
        bodylayer.mirror = true;
        setRotation(bodylayer, 0F, 0F, 0F);
        leftarmlayer = new ModelRenderer(this, 32, 48);
        leftarmlayer.addBox(0F, 0F, 0F, 4, 12, 4);
        leftarmlayer.setRotationPoint(4F, 0F, -2F);
        leftarmlayer.setTextureSize(128, 128);
        leftarmlayer.mirror = true;
        setRotation(leftarmlayer, 0F, 0F, 0F);
        winga = new ModelRenderer(this, 0, 64);
        winga.addBox(0F, 0F, 0F, 26, 32, 0);
        winga.setRotationPoint(-30F, -11F, 5F);
        winga.setTextureSize(128, 128);
        winga.mirror = true;
        setRotation(winga, 0F, 0F, -0.1745329F);
        wingb = new ModelRenderer(this, 52, 64);
        wingb.addBox(0F, 0F, 0F, 26, 32, 0);
        wingb.setRotationPoint(4F, -15.8F, 5F);
        wingb.setTextureSize(128, 128);
        wingb.mirror = true;
        setRotation(wingb, 0F, 0F, 0.1745329F);
        Shape = new ModelRenderer(this, 0, 97);
        Shape.addBox(0F, 0F, 0F, 14, 16, 0);
        Shape.setRotationPoint(-2F, -10F, -13F);
        Shape.setTextureSize(128, 128);
        Shape.mirror = true;
        setRotation(Shape, -0.7853982F, -1.570796F, -0.5235988F);
        Piece1 = new ModelRenderer(this, "Piece1");
        Piece1.setRotationPoint(6F, 0F, 0F);
        setRotation(Piece1, 1.712798F, 0F, 0F);
        Piece1.mirror = true;
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        head.render(f5);
        body.render(f5);
        rightarm.render(f5);
        leftarm.render(f5);
        rightleg.render(f5);
        leftleg.render(f5);
        rightarmlayer.render(f5);
        headlayer.render(f5);
        leftleglayer.render(f5);
        rightleglayer.render(f5);
        bodylayer.render(f5);
        leftarmlayer.render(f5);
        winga.render(f5);
        wingb.render(f5);
        Shape.render(f5);
        Piece1.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5);
    }

}
